/**
 * Field and Section Labels Configuration
 *
 * Defines human-readable labels for all patient data fields and sections.
 *
 * FIELD_LABELS: Maps section keys (section1, section2...) to field label dictionaries.
 * Used by SectionCard component to display formatted field names.
 *
 * SECTION_LABELS: Maps semantic section keys to section titles.
 * Example: 'admin' -> '1: INFORMATION ADMINISTRATIVE'
 */

export const FIELD_LABELS: Record<string, Record<string, string>> = {
  section1: {
    nomPatient: "Nom du patient",
    anneeNaissance: "Année de naissance",
    age: "Âge",
    sexe: "Sexe",
    profession: "Profession",
    secteur: "Secteur",
    kineExaminateur: "Kiné examinateur",
    dateBilan: "Date du bilan",
    idPatient: "ID Patient",
    idBilan: "ID Bilan",
  },
  section2: {
    poids: "Poids",
    taille: "Taille",
    imc: "IMC",
  },
  section3: {
    antecedentsLBP: "Antécédents LBP",
    episodeInitial: "Épisode initial",
    modeApparition: "Mode d'apparition",
    recidive: "Récidive",
    pireEpisode: "Pire épisode",
    dureeTotale: "Durée totale LBP",
    typeLBP: "Type LBP",
  },
  section4: {
    nrsRepos: "NRS douleur au repos",
    nrsActivite: "NRS douleur à l'activité",
    nrsMax: "NRS douleur max",
    horaireDouleur: "Horaire douleur",
    variationJournaliere: "Variation journalière",
    facteursAggravants: "Facteurs aggravants",
    facteursSoulageants: "Facteurs soulageants",
    evolution: "Évolution",
  },
  section5: {
    douleurArticulaire: "Douleur articulaire",
    douleurMyofasciale: "Douleur myofasciale",
    douleurNeurologique: "Douleur neurologique",
    sensibilisationCentrale: "Sensibilisation centrale",
    deficitSensorimoteur: "Déficit sensorimoteur",
    caractereSensations: "Caractère des sensations",
    observationsMecanismes: "Observations mécanismes",
  },
  section6: {
    flexionAvant: "Flexion avant",
    flexionAvantNrs: "NRS Flexion avant",
    extension: "Extension",
    extensionNrs: "NRS Extension",
    inclinaisonDroit: "Inclinaison latérale droite",
    inclinaisonDroitNrs: "NRS Inclinaison D",
    inclinaisonGauche: "Inclinaison latérale gauche",
    inclinaisonGaucheNrs: "NRS Inclinaison G",
    rotationDroit: "Rotation droite",
    rotationDroitNrs: "NRS Rotation droite",
    rotationGauche: "Rotation gauche",
    rotationGaucheNrs: "NRS Rotation gauche",
    mouvementsCombines: "Mouvements combinés",
    mouvementsCombinesNrs: "NRS Mouvements combinés",
    mobiliteSegmentaire: "Mobilité segmentaire PA",
    mobiliteSegmentaireNrs: "NRS Mobilité segmentaire",
    hanche: "Hanche",
    hancheNrs: "NRS Hanche",
    slrDroit: "SLR droit",
    slrGauche: "SLR gauche",
    asymetrieSlr: "Asymétrie SLR",
    slumpTest: "Test de slump",
    pkb: "PKB",
    forceMusculaire: "Force musculaire",
    reflexes: "Réflexes",
    sensation: "Sensation",
    sensationLocalisation: "Localisation sensation",
    profilSensoriel: "Profil sensoriel",
    tensionMusculaire: "Tension musculaire",
    triggerPoints: "Points trigger",
    triggerPointsLocalisation: "Localisation trigger points",
    hypersensibilite: "Hypersensibilité à la pression",
    spasmeMusculaire: "Spasme musculaire",
    spasmeLocalisation: "Localisation spasme",
    localisation: "Localisation",
    signesMeninges: "Signes méningés",
    hypersensibilitePression: "Hypersensibilité à la pression",
    zoneLombaire: "Zone lombaire",
    zoneControle: "Zone contrôle",
    testSorensen: "Test de Sorensen",
    testItoShirado: "Test Ito-Shirado",
    coreStrengthIndex: "Indice de force centrale",
    sidePlank: "Planche latérale",
    controlSensoriMoteur: "Contrôle sensorimoteur",
  },
  section7: {
    scoreSBT: "SBT (Start Back Tool)",
    scoreCSI: "Core Strength Index",
    scoreODI: "Oswestry Disability Index",
    scorePCS: "Pain Catastrophizing Scale",
    scoreAnxiete: "Anxiété HADS",
    scoreDepression: "Dépression HADS",
    scoreFabqTravail: "FABQ Travail",
    scoreFabqActivite: "FABQ Activité",
    scoreWAI: "WAI",
    scoreIPAQ: "IPAQ",
    scoreIPAQ_MET: "IPAQ (MET)",
    scorePSFS: "PSFS",
    scorePSFS_Scores: "Scores PSFS",
    qualiteVie: "Qualité de vie",
    autresQuestionnaires: "Autres questionnaires",
  },
  section8: {
    redFlags: "Drapeaux rouges",
    detailsRedFlags: "Détails drapeaux rouges",
    contreIndications: "Contre-indications",
    allergies: "Allergies",
    medications: "Médications pertinentes",
    examensMedicaux: "Examens médicaux",
    instabiliteRachidienne: "Instabilité rachidienne",
    signesInstabilite: "Signes instabilité",
    limitationManuelle: "Limitation traitement manuel",
    anticoagulation: "Anticoagulation",
    traitementAnticoagulation: "Traitement anticoagulation",
    grossesse: "Grossesse",
    trimestreGrossesse: "Trimestre grossesse",
    adaptationsGrossesse: "Adaptations grossesse",
    etatGeneral: "État général",
  },
  section9: {
    motifArticulaire: "Motif articulaire",
    motifMyofascial: "Motif myofascial",
    motifNeural: "Motif neural",
    sensibilisationCentrale: "Sensibilisation centrale",
    controleSensorimoteur: "Contrôle sensorimoteur",
  },
  section10: {
    frequence: "Fréquence thérapie",
    hasTherapieManuelle: "Thérapie manuelle",
    typesTherapieManuelle: "Types thérapie manuelle",
    hasExercices: "Thérapie par exercice",
    typesExercices: "Types exercices",
    hasNeurodynamique: "Neurodynamique",
    typesNeurodynamique: "Types neurodynamique",
    hasEducation: "Éducation patient",
    sujetsEducation: "Sujets éducation",
    modalitesSup: "Modalités supplémentaires",
  },
  section11: {
    comprehensionDiagnostic: "Compréhension du diagnostic",
    inquietudes: "Inquiétudes",
    perceptionGravite: "Perception de gravité",
    autoEfficacite: "Auto-efficacité",
    croyanceControle: "Croyance de contrôle",
  },
  section12: {
    dureeTraitement: "Durée estimée traitement",
    nbSeances: "Nombre de séances",
    facteursPositifs: "Facteurs pronostiques positifs",
    facteursNegatifs: "Facteurs pronostiques négatifs",
    objectifsCourtTerme: "Objectifs à court terme",
    objectifsLongTerme: "Objectifs à long terme",
    attentesRealistes: "Attentes réalistes",
    anticipationGuerison: "Anticipation guérison",
    yellowFlags: "Drapeaux jaunes",
    soutienSocial: "Soutien social",
    stresseurs: "Stresseurs identifiés",
    pointReevaluation: "Point de réévaluation",
    orientationSpecialise: "Orientation spécialisée",
    barrieresTraitement: "Barrières au traitement",
  },
  section13: {
    activitesQuotidiennes: "Activités quotidiennes limitées",
    loisirs: "Loisirs/Sports",
    activitesAnterieures: "Activités antérieures",
    activitesActuelles: "Actuellement",
    tempsAssis: "Temps assis",
    tempsDebout: "Temps assis/debout (Debout)",
    tempsMarche: "Temps assis/debout (Marche)",
    tempsAssisQuotidien: "Temps assis quotidien",
    tempsEcran: "Temps écran",
    sedentarite: "Sédentarité",
    statutPro: "Statut professionnel",
    joursAbsence: "Jours d'absence travail",
    limitationsPro: "Limitations professionnelles",
    tachesImpossibles: "Tâches impossibles",
    tachesDifficiles: "Tâches difficiles",
    attentesRetourTravail: "Attentes retour au travail",
    delaiRetourTravail: "Délai anticipé",
    confianceRetourTravail: "Confiance retour",
    modifPoste: "Modifications poste possibles",
    typeModifPoste: "Type modification",
  },
  section14: {
    defautsPosturaux: "Défauts posturaux",
    facteursBiomeca: "Facteurs biomécaniques",
    facteursLifestyle: "Facteurs lifestyle",
    facteursHormonaux: "Facteurs hormonaux/métaboliques",
    ergonomieTravail: "Ergonomie travail",
    posteOptimise: "Poste optimisé",
    recommandationsErgonomie: "Recommandations",
    facteursPsycho: "Facteurs psychosociaux",
    systemeSante: "Système santé/culture",
    conceptionBiopsychosociale: "Conception biopsychosociale",
    attentesCulturelles: "Attentes culturelles",
    attenteGuerisonRapide: "Attente guérison rapide",
    approchePreferee: "Approche préférée",
    compliance: "Compliance anticipée",
    barrieresCompliance: "Barrières compliance",
  },
  section15: {
    pgic: "PGIC",
    etatPGIC: "État PGIC",
    satisfaction: "Satisfaction",
    relationTherapeute: "Relation thérapeute",
    gasScore: "GAS",
    progressionGAS: "Progression objectifs",
  },
  section16: {
    resumeClinique: "Résumé clinique",
    observationsGlobales: "Observations globales",
    impressionGenerale: "Impression générale",
    notesSup: "Notes supplémentaires",
    planTraitement: "Plan de traitement",
  },
  section17: {
    pathology: "Pathologie",
    sourcesOfSymptoms: "Sources des symptômes",
    painType: "Type de douleur",
    impairments: "Déficits",
    painMechanisms: "Mécanismes de douleur",
    precautions: "Précautions",
    patientPerspectives: "Perspectives du patient",
    activityParticipation: "Activité/Participation",
    contributingFactors: "Facteurs contribuants",
    managementPrognosis: "Gestion et pronostic",
  },
  section18: {
    confianceExtraction: "Confiance extraction",
    isComplete: "Complétude",
    needsReview: "Révision manuelle",
    modifiePar: "Modifié par",
    dateModification: "Date modification",
  },
};

export const SECTION_LABELS: Record<string, string> = {
  admin: "1: INFORMATION ADMINISTRATIVE",
  anthropo: "2: DONNÉES ANTHROPOMÉTRIQUES",
  pathologie: "3: PATHOLOGIE LOMBAIRE",
  symptomes: "4: SYMPTÔMES - INTENSITÉ DOULEUR",
  mecanismes: "5: MÉCANISMES DE DOULEUR",
  tests: "6: TESTS FONCTIONNELS - MOBILITÉ LOMBAIRE",
  scores: "7: QUESTIONNAIRES VALIDÉS - SCORES",
  redFlags: "8: DRAPEAUX ROUGES & PRÉCAUTIONS",
  mecanismesResume: "9: MÉCANISMES DOULEUR",
  gestion: "10: PLAN DE GESTION & RECOMMANDATIONS",
  perspectives: "11: PERSPECTIVES ET CROYANCES DU PATIENT",
  pronostic: "12: PRONOSTIC",
  activites: "13: ACTIVITÉS ET PARTICIPATION",
  facteurs: "14: FACTEURS CONTRIBUANTS",
  satisfaction: "15: SATISFACTION",
  observations: "16: OBSERVATIONS CLINIQUES & NOTES",
  hypothese: "17: HYPOTHÈSE DE TRAVAIL",
  qualite: "18: CONTRÔLE QUALITÉ",
};
