export const FIELD_LABELS: Record<string, Record<string, string>> = {
  admin: {
    nom: "NOM ET PRÉNOM DU PATIENT",
    anneeNaiss: "ANNÉE DE NAISSANCE",
    age: "AGE",
    sexe: "SEXE",
    profession: "PROFESSION",
    secteur: "SECTEUR D'ACTIVITÉ",
    kine: "KINÉ EXAMINATEUR",
    dateBilan: "DATE BILAN",
    idPatient: "ID PATIENT",
    idBilan: "ID BILAN",
  },
  anthropo: {
    poids: "POIDS",
    taille: "TAILLE",
    imc: "IMC CALCULÉ",
  },
  pathologie: {
    antecedents: "ANTÉCÉDENTS LBP",
    episode: "EPISODE INITIAL",
    traumatisme: "TRAUMATISME",
    recidive: "RÉCIDIVE",
    pireEpisode: "PIRE EPISODE",
    duree: "DURÉE TOTALE LBP",
    type: "TYPE LBP",
  },
  symptomes: {
    nrsRepos: "NRS DOULEUR AU REPOS",
    nrsActivite: "NRS DOULEUR À L'ACTIVITÉ",
    nrsMax: "NRS DOULEUR MAXIMUM",
    horaire: "HORAIRE DOULEUR",
    variation: "VARIATION JOURNALIÈRE",
    aggravants: "FACTEURS AGGRAVANTS",
    soulagants: "FACTEURS SOULAGEANTS",
    evolution: "ÉVOLUTION",
  },
  mecanismes: {
    articulaire: "DOULEUR ARTICULAIRE",
    myofascial: "DOULEUR MYOFASCIALE",
    neurologique: "DOULEUR NEUROLOGIQUE",
    sensitization: "SENSIBILISATION CENTRALE",
    sensorimotor: "DÉFICIT SENSORIMOTOR",
    caractereNeurologique: "CARACTÈRE SENSATIONS",
    observations: "OBSERVATIONS MÉCANISMES",
  },
  tests: {
    flexion: "FLEXION AVANT",
    extension: "EXTENSION",
    inclinDroit: "INCLINAISON LATÉRALE DROIT",
    inclinGauche: "INCLINAISON LATÉRALE GAUCHE",
    rotationDroit: "ROTATION DROITE",
    rotationGauche: "ROTATION GAUCHE",
    combinaison: "COMBINAISON DE MOUVEMENTS",
    mobilitePA: "MOBILITÉ SEGMENTAIRE PA",
    hanche: "HANCHE",
    slrDroit: "SLR DROIT",
    slrGauche: "SLR GAUCHE",
    asymetrieSLR: "ASYMÉTRIE SLR",
    slumpTest: "TEST DE SLUMP",
    pkb: "PKB",
    forceMusculaire: "FORCE MUSCULAIRE",
    reflexes: "RÉFLEXES",
    sensation: "SENSATION",
    profilSensoriel: "PROFIL SENSORIEL",
    signeMeninges: "SIGNES MÉNINGÉS",
    tensionMusculaire: "TENSION MUSCULAIRE",
    triggerPoints: "POINTS TRIGGER",
    sensibiliteSession: "HYPERSENSIBILITÉ À LA PRESSION",
    spasmeMusculaire: "SPASME MUSCULAIRE",
    sorensen: "SORENSEN",
    itoShirado: "ITO SHIRADO",
    csiStrength: "INDICE DE FORCE CENTRALE",
    sidePlank: "PLANCHE LATÉRALE D/G",
    csm: "CSM (PLANCHE, BASCULE PELVIENNE, PONT...)",
  },
  scores: {
    sbt: "SBT (OUTIL DE DÉPISTAGE START BACK)",
    csi: "SCORE CSI",
    odi: "SCORE ODI",
    pcs: "SCORE PCS",
    hadsAnxiete: "SCORE HADS ANXIÉTÉ",
    hadsDepression: "SCORE HADS DÉPRESSION",
    fabqTravail: "SCORE FABQ TRAVAIL",
    fabqActivite: "SCORE FABQ ACTIVITÉ",
    wai: "SCORE WAI",
    ipaq: "SCORE IPAQ",
    psfs: "SCORE PSFS",
    sf36: "SCORE SF-36 / EQ-5D",
    autresQuestionnaires: "AUTRES QUESTIONNAIRES",
  },
  redFlags: {
    detectes: "DRAPEAUX ROUGES DÉTECTÉS",
    contraindications: "CONTRE-INDICATIONS",
    allergies: "ALLERGIES",
    medications: "MÉDICATIONS PERTINENTES",
    examensMedicaux: "EXAMEN MÉDICAUX",
    instabiliteRachidienne: "INSTABILITÉ RACHIDIENNE",
    limitationMT: "LIMITATION TRAITEMENT MANUEL",
    anticoagulation: "ANTICOAGULATION",
    grossesse: "GROSSESSE",
    etatGeneral: "ÉTAT GÉNÉRAL",
  },
  mecanismesResume: {
    motifArticulaire: "MOTIF ARTICULAIRE",
    motifMyofascial: "MOTIF MYOFASCIAL",
    motifNeural: "MOTIF NEURAL",
    sensibilisationCentrale: "SENSIBILISATION CENTRALE",
    controleSensorimotor: "CONTRÔLE SENSORIMOTEUR",
  },
  gestion: {
    frequence: "FRÉQUENCE THÉRAPIE",
    therapieManuelle: "THÉRAPIE MANUELLE",
    exercice: "THÉRAPIE PAR EXERCICE",
    neurodynamique: "THÉRAPIE PAR NEURODYNAMIQUE",
    education: "ÉDUCATION PATIENT",
    modalites: "MODALITÉS SUPPLÉMENTAIRES",
  },
  perspectives: {
    comprehension: "COMPRÉHENSION DU DIAGNOSTIC",
    perception: "PERCEPTION DE GRAVITÉ",
    autoEfficacite: "AUTO-EFFICACITÉ",
  },
  pronostic: {
    dureeEstimee: "DURÉE ESTIMÉE TRAITEMENT",
    nombreSeances: "NOMBRE DE SÉANCES ESPÉRÉES",
    facteurPositif: "FACTEURS PRONOSTIQUES POSITIFS",
    facteurNegatif: "FACTEURS PRONOSTIQUES NÉGATIFS",
    objectifCourt: "OBJECTIFS À COURT TERME",
    objectifLong: "OBJECTIFS À LONG TERME",
    attentesRealistes: "ATTENTES RÉALISTES",
    anticipationGuérison: "PATIENT ANTICIPE GUÉRISON",
    yellowFlags: "DRAPEAUX JAUNES",
    soutienSocial: "SOUTIEN SOCIAL",
    stresseurs: "STRESSEURS IDENTIFIÉS",
    reevaluation: "POINT DE RÉÉVALUATION",
    orientationSpecialisee: "BESOIN ORIENTATION SPÉCIALISÉE",
    barrieres: "BARRIÈRES ANTICIPÉES AU TRAITEMENT",
  },
  activites: {
    activitesLimitees: "ACTIVITÉS QUOTIDIENNES LIMITÉES",
    activitesAnterieures: "ACTIVITÉS ANTÉRIEURES",
    activitesActuelles: "ACTIVITÉS ACTUELLES",
    tempsAssis: "TEMPS ASSIS/DEBOUT TOLÉRÉ",
    comportementSedentaire: "COMPORTEMENT SÉDENTAIRE",
    statutProfessionnel: "STATUT PROFESSIONNEL",
    joursAbsence: "JOURS D'ABSENCE TRAVAIL",
    limitationsProfessionnelles: "LIMITATIONS PROFESSIONNELLES",
    delaiRetourTravail: "DÉLAI ANTICIPÉ RETOUR TRAVAIL",
    confianceRetourTravail: "CONFIANCE RETOUR TRAVAIL",
    modificationPoste: "MODIFICATIONS POSTE POSSIBLES",
  },
  facteurs: {
    defautsPosturaux: "DÉFAUTS POSTURAUX IDENTIFIÉS",
    facteursBiomécaniques: "FACTEURS BIOMÉCANIQUES",
    styleVie: "FACTEURS DE STYLE DE VIE",
    hormonal: "FACTEURS HORMONAUX/MÉTABOLIQUES",
    posteOptimise: "POSTE OPTIMISÉ",
    psychosociaux: "FACTEURS PSYCHOSOCIAUX MAJEURS",
    systemeSante: "SYSTÈME SANTÉ/CULTURE",
    attenteGuerison: "ATTENTE GUÉRISON RAPIDE",
    compliance: "COMPLIANCE ANTICIPÉE",
    complianceBarrieres: "BARRIÈRES",
  },
  satisfaction: {
    pgic: "PGIC",
    treatmentSatisfaction: "SATISFACTION DU TRAITEMENT",
    relationTherapeute: "RELATION THÉRAPEUTE",
    gas: "GAS (ÉCHELLE D'ATTEINTE DES OBJECTIFS)",
  },
  observations: {
    resume: "RÉSUMÉ CLINIQUE",
    observationsGlobales: "OBSERVATIONS GLOBALES",
    impressionGenerale: "IMPRESSION GÉNÉRALE",
    notes: "NOTES SUPPLÉMENTAIRES",
    planTraitement: "PLAN DE TRAITEMENT RECOMMANDÉ",
  },
  hypothese: {
    pathologie: "PATHOLOGIE",
    sources: "SOURCES DES SYMPTÔMES",
    painType: "TYPE DE DOULEUR",
    impairments: "DÉFICITS / LIMITATIONS",
    painMechanisms: "MÉCANISMES DE DOULEUR",
    precautions: "PRÉCAUTIONS",
    patientsPerspectives: "PERSPECTIVES DU PATIENT",
    activityParticipation: "ACTIVITÉS ET PARTICIPATION",
    contributingFactors: "FACTEURS CONTRIBUANTS",
    managementPrognosis: "GESTION ET PRONOSTIC",
  },
  qualite: {
    confiance: "CONFIANCE EXTRACTION",
    completude: "DONNÉES COMPLÈTES",
    revision: "RÉVISION MANUELLE REQUISE",
    modifiePar: "MODIFIÉ PAR",
    dateModif: "DATE MODIFICATION",
  },
};

export const SECTION_LABELS: Record<string, string> = {
  admin: "1: INFORMATION ADMINISTRATIVE",
  anthropo: "2: DONNÉES ANTHROPOMÉTRIQUES",
  pathologie: "3: PATHOLOGIE LOMBAIRE",
  symptomes: "4: SYMPTÔMES - INTENSITÉ DOULEUR",
  mecanismes: "5: MÉCANISMES DE DOULEUR",
  tests: "6: TESTS FONCTIONNELS - MOBILITÉ LOMBAIRE",
  scores: "7: QUESTIONNAIRES VALIDÉS - SCORES",
  redFlags: "8: DRAPEAUX ROUGES & PRÉCAUTIONS",
  mecanismesResume: "9: MÉCANISMES DOULEUR",
  gestion: "10: PLAN DE GESTION & RECOMMANDATIONS",
  perspectives: "11: PERSPECTIVES ET CROYANCES DU PATIENT",
  pronostic: "12: PRONOSTIC",
  activites: "13: ACTIVITÉS ET PARTICIPATION",
  facteurs: "14: FACTEURS CONTRIBUANTS",
  satisfaction: "15: SATISFACTION",
  observations: "16: OBSERVATIONS CLINIQUES & NOTES",
  hypothese: "17: HYPOTHÈSE DE TRAVAIL",
  qualite: "18: CONTRÔLE QUALITÉ",
};
